version: '3'
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    # Es kann auch die Datei direkt verlinkt werden.
    # env_file: 
    #   - ./.env
    environment:
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - check-db-started
    networks:
      - app-network
      - proxy-network

  db:
    image: postgres:latest
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASS}
      POSTGRES_DB: ${APP_DB_NAME}
    
    networks:
      - app-network

  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:5432'
    networks:
      - app-network

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-network

networks:
  app-network:
  proxy-network: